version: '3.7'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    expose:
      - 6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis-data:/data
      - ./configs/redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf

  go-cqhttp:
    image: silicer/go-cqhttp
    restart: always
    container_name: go-cqhttp
    depends_on:
      - nonebot
    volumes:
      - ./data/go-cqhttp/data:/data/data
      - ./data/go-cqhttp/logs:/data/logs
      - ./configs/go-cqhttp.yml:/data/config.yml:ro

  nonebot:
    build: ./nonebot
    restart: always
    container_name: nonebot
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 9999
    depends_on:
      - redis
    volumes:
      - ./bilibili-helper:/data/bilibili-helper
      - ./certfiles:/data/certfiles
    command: python3 bot.py

  api:
    build: ./api
    restart: always
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - redis
    volumes:
      - ./certfiles:/data/certfiles
    command: python3 server.py